

import Foundation

// 1044. Longest Duplicate Substring

class LongestDupSubstring0 {
   func longestDupSubstring(_ S: String) -> String {
        // base value for the rolling hash function
        let base = 26
        // modulus value for the rolling hash function
        // large number to avoid hashing collisions
        let modulus = Int(pow(Double(2), Double(37)))
        
        let nums = S.map { Int($0.asciiValue!) % base }
        var result: (index: Int, length: Int) = (-1, -1)
        
        // binary search to find the longestDupSubstring length
        var left = 0
        var right = nums.count - 1
        while left <= right {
            let length = (left + right) / 2
            if length == 0 {
                break
            }
            
            let index = search(nums, length, modulus, base)
            if index < 0 {
                right = length - 1
            } else {
                if length > result.length {
                    result = (index, length)
                }
                left = length + 1
            }
        }
        
        if result.length <= 0 {
            return ""
        }
        
        let startIndex = S.index(S.startIndex, offsetBy: result.index)
        let endIndex = S.index(startIndex, offsetBy: result.length)
        return String(S[startIndex..<endIndex])
    }
    
    func search(_ nums: [Int], _ length: Int, _ modulus: Int, _ base: Int) -> Int {
        var hashSet = Set<Int>()
        
        var hashValue = initialHash(nums, length, modulus, base)
        hashSet.insert(hashValue)
        
        var hashMultiplier = 1
        for i in 0..<length {
            hashMultiplier = (hashMultiplier * base) % modulus
        }
        
        for i in 1...(nums.count - length) {
            hashValue = nextHash(hashValue, nums[i - 1], nums[i + length - 1], hashMultiplier, modulus, base)
            if hashSet.contains(hashValue) {
                return i
            }
            hashSet.insert(hashValue)
        }
        return -1
    }
    
    func initialHash(_ nums: [Int], _ length: Int, _ modulus: Int, _ base: Int) -> Int {
        var total = 0
        for i in 0..<length {
            total = (total * base + nums[i]) % modulus
        }
        return total
    }
    
    func nextHash(_ prevHash: Int, _ dropped: Int, _ added: Int, _ hashMultiplier: Int, _ modulus: Int, _ base: Int) -> Int {
        let hashValue = (prevHash * base - (dropped * hashMultiplier) % modulus + modulus) % modulus
        return (hashValue + added) % modulus
    }
}

class LongestDupSubstring1 {
    final class TrieNode {
        var next: [TrieNode?]!
        var i: Int = 0
        var depth: Int = 0
        
        var isLeaf: Bool {
            return next == nil
        }

        init(_ i: Int, _ depth: Int) {
            self.i = i
            self.depth = depth
        }
        
        func setNext(_ index: Int, _ v: TrieNode) {
            if (next == nil) {
               next = Array(repeating: nil, count: 26)
            }
            next[index] = v
        }
    }
    
    let charA: Int = Int(Character("a").asciiValue!)
    var sArray: [Int]!
    
    func longestDupSubstring(_ S: String) -> String {
        sArray = Array(S).map { Int($0.asciiValue!) - charA }
        var maxLo = 0
        var maxLength = 0
        
        let root = TrieNode(0, 0)
        var i = 1
        while ((i + maxLength) < S.count) {
            let len = addNew(root, i)
            if (len > maxLength) {
                maxLength = len
                maxLo = i
            }
            i += 1
        }
        print(maxLo)
        print(maxLength)
        let s = sArray[maxLo..<(maxLo + maxLength)]
        return String(s.map {
            Character(UnicodeScalar($0 + charA)!)
        })
    }

    func getIndex(_ i: Int, _ depth: Int) -> Int {
        return sArray[i + depth]
    }

    func addNew(_ node: TrieNode, _ i: Int) -> Int {
        let depth = node.depth
        if (i + depth >= sArray.count) {
            return depth
        }
        if node.isLeaf {
            let index = getIndex(node.i, node.depth)
            node.setNext(index, TrieNode(node.i, depth + 1))
        }
        let c = getIndex(i, node.depth)
        if let x = node.next[c] {
            return addNew(x, i)
        }
        node.setNext(c, TrieNode(i, depth + 1))
        return depth
    }
}


let v = LongestDupSubstring0()
/*
duration {
    v.longestDupSubstring("aananana")
    v.longestDupSubstring("banana")

v.longestDupSubstring("abcd")
v.longestDupSubstring("moplvidmaagmsiyyrkchbyhivlqwqsjcgtumqscmxrxrvwsnjjvygrelcbjgbpounhuyealllginkitfaiviraqcycjmskrozcdqylbuejrgfnquercvghppljmojfvylcxakyjxnampmakyjbqgwbyokaybcuklkaqzawageypfqhhasetugatdaxpvtevrigynxbqodiyioapgxqkndujeranxgebnpgsukybyowbxhgpkwjfdywfkpufcxzzqiuglkakibbkobonunnzwbjktykebfcbobxdflnyzngheatpcvnhdwkkhnlwnjdnrmjaevqopvinnzgacjkbhvsdsvuuwwhwesgtdzuctshytyfugdqswvxisyxcxoihfgzxnidnfadphwumtgdfmhjkaryjxvfquucltmuoosamjwqqzeleaiplwcbbxjxxvgsnonoivbnmiwbnijkzgoenohqncjqnckxbhpvreasdyvffrolobxzrmrbvwkpdbfvbwwyibydhndmpvqyfmqjwosclwxhgxmwjiksjvsnwupraojuatksjfqkvvfroqxsraskbdbgtppjrnzpfzabmcczlwynwomebvrihxugvjmtrkzdwuafozjcfqacenabmmxzcueyqwvbtslhjeiopgbrbvfbnpmvlnyexopoahgmwplwxnxqzhucdieyvbgtkfmdeocamzenecqlbhqmdfrvpsqyxvkkyfrbyolzvcpcbkdprttijkzcrgciidavsmrczbollxbkytqjwbiupvsorvkorfriajdtsowenhpmdtvamkoqacwwlkqfdzorjtepwlemunyrghwlvjgaxbzawmikfhtaniwviqiaeinbsqidetfsdbgsydkxgwoqyztaqmyeefaihmgrbxzyheoegawthcsyyrpyvnhysynoaikwtvmwathsomddhltxpeuxettpbeftmmyrqclnzwljlpxazrzzdosemwmthcvgwtxtinffopqxbufjwsvhqamxpydcnpekqhsovvqugqhbgweaiheeicmkdtxltkalexbeftuxvwnxmqqjeyourvbdfikqnzdipmmmiltjapovlhkpunxljeutwhenrxyfeufmzipqvergdkwptkilwzdxlydxbjoxjzxwcfmznfqgoaemrrxuwpfkftwejubxkgjlizljoynvidqwxnvhngqakmmehtvykbjwrrrjvwnrteeoxmtygiiygynedvfzwkvmffghuduspyyrnftyvsvjstfohwwyxhmlfmwguxxzgwdzwlnnltpjvnzswhmbzgdwzhvbgkiddhirgljbflgvyksxgnsvztcywpvutqryzdeerlildbzmtsgnebvsjetdnfgikrbsktbrdamfccvcptfaaklmcaqmglneebpdxkvcwwpndrjqnpqgbgihsfeotgggkdbvcdwfjanvafvxsvvhzyncwlmqqsmledzfnxxfyvcmhtjreykqlrfiqlsqzraqgtmocijejneeezqxbtomkwugapwesrinfiaxwxradnuvbyssqkznwwpsbgatlsxfhpcidfgzrc")


v.longestDupSubstring("bwvzoubsovtdpokbjgubpkzsdmxpdxwrkjzjbhcuvppjowoaapfpaqmgpkflwookqdujdfqsifdbkmwqfumwhotpdmevmshumjcdquspnihgceaedgxjgrtjdxqacznaluiiwrivaulamzyecdpyfyxmiavwkqvbybabmshszoslhxzhmaqtvhbnznnxuyctrbywifcuguutkdxchpyxurmskwbygnbtatoxwesmtzchjlrnqsjxanoemmzsqcraykiszrieoaqcwcwlyorrcvlamxztujsglqcwjmqvcmmuwwjgkdfhfxfahlefserldejymbhgdddlwjllantqxeivdbrsbjdcsgrcngejbfvwdjbaffvarzdkizozlszqvzsyszqklvinaypeqyppcyafzqkdlreddrmbxwiikymgcqaghptuvbgkoebirotkfdxcfxeykqvdqlbmnbpgumksbsdwdbyqfdwdqpfustxqorwpxyatjuiocqjytiqzymfkyagtxqypmwnppqwpoltglrpalpextaglktgzauzwxnzgwqfvxitoqkiqcacpcetzscypoumazhyjtqhflnihtmboxmqqqvahqsukxebqnyxpyoiczdjikslukjvgeejnirpijjkhdjrfkjrvvqlrdpzwfyredgxljfjmbtrkpdydmpqqvywtqmdcyrtapmqwhkaocdzkamlbunnfhfcfpoechlqripwsmskcprihcnptbqyqxdnhewuehycuaxbzxbftjaqsfqtvmfvisepjnrzqibkbwtncipwcejllhlqxylwzmquwqgbizbumshhoxwvexjxgiexmjfsrfnplybfdouqggsntludnaznsbnloorlwkhicbzrfvcqohmlzojfdsyzjniyoinfszmaelknerpwgmctnkjjnixlmxjdvpxjjbonmfxrxgpxrculamkmwwnrxgsjlwdohonruecrtuknjjjgsmcctqdfsttcikawjaowskacuretxcdqnkapiiiwezklfnbayedclkkdwdqqsmxqupcphgdmaldcnidadhpvyvbsprbrqpifrpdsjgwvoxumxeuybmcwbmuyacvrfqfkuszjpwyjwbmrhbbvdmhwrowsqahmeexucshsvknchkzljwoztqgrthoeldityevjljhavuqcxgwzcoyvsjoxvmlrxtytlomorbfkskzkfzhbhqjumnwzbfaalogdwztbeirzxitgbmfcwkkgfwapubspmhuygtfhsxjcoklybqoultxvmtactpqqsgewzzguxndxouiacalpopiovashsfcnftuaxaafwjhruheabclgjjyxpaiyuqjybpkdzkyrfnxfwcvdedcfqiseljtebxzcjqmqkhyiurdiybznjnkzaqthrpanhflnunqucliwsdttzbkmndrckzucllnjosvryowfkielbdziuqhiilbbsfbllxjyodgurluibsfjxqoupbxfpxkjscslirbszjmhklgevhdrqykonnnekacqtcworjpgxuraikciaburspaldpihnyafojwmclckulomsyyzxonthymcffhlxjfzonzxpwkpihianrywxejbghxrvsadkhljtubrenaemecmmvesijfqpthrkhiqhdrkvxlrkciaklncrnxzdhcsuaesjmbjlupwvwjfelxipbaligpeojbrvosyimousrqaenebgeleuuybixbwirltnctluazywoqcefcrejgtlfruyiotcbmubuqxbdthtakywfopbvkysddivfaaqaylpoadazdskcuhklvuqmbguwtlaawymbkveoszsysramyowewkheriglqwqejursmaiyhmnrlxryolizwsywgaizflzghtammlntphjmvlvyujgfsjlscpjhavxbeutapfieswtpldeeuxetbqphkqibwdzfeqbjxaryeogyirhleulfeeprmshdmiikfhuqxxpxdryenhdzgxojixhcjswllduemothoxzzpbiapvinihgucazbvggihobmscpijwcavhqxlcenuqjjjpehpreyccucfiecnyflxojxdskncvvdpwzrlwkfhhvgcdeevtflgwypgvvuzlntncpqiczyzxoxsfabybcxlarysptirnzpbzfzlagchruxjfzibrwfyxtyydathyctagcnokpwqfiowsdjvfrnzogemfchwitmoqsoezqdkwefjufdnvnhogqzzcqngkgaiwoqofwjtdygktqvmzcwwmzemvxlgryjjzoyguwjuczziosldbwwygftujlpzanbszeaakidazfpdtbnrowhnlqgyvssziolsfedivgsqvamcliuqeemeorxlrzyofbiozdpuobjwuxglvuuvxebvsnxomfziirlvhuqxjwunehjcqjnmlliqkywwmguloxmapflwhoddpqzduyfkizkneooifsndynggljsfbjcfzahmkambrojzdbatgtimxiisguvdpftjcwmjxbqyaltbgvfefyqwnminsuqraztojpshmlrqtrbpyiekbanjjndnfkhlyihbmxvwyrfomlpcsbrkrptkfyapjctyoruxdwrzjgcrfsxytlripxckhabdqnxwyiidegjwsqvqckjhlmlvdhfnlclizhdpsvmsrkbrzahcuvonpizhyrwilmbmwexzzohvlhzfcqcwhfgamikhkhfrwmymvxrmbypdurouthrlzubtclfltanroeegkfjqqrjxwgyzymcoopcubqvghnckoccjdicffridjupfylgseipqgbshoesjjcjhpyodpituvipopeizgwortgqvotiyfzfnkixcsbuywrxowetievuudmwtnxcbbxpotkcuqmxczzldimrdulntjsieciuebztdtfftligeybplqculadfvnqqxdbrnjqgptjlhqrutfvsiencukxpioekrszfgryxsbcaqaabbsvskhpivnedwejrnooejfvfmozywtkntdcpphrwnnqdvnakujmrqymxgetisbvllvcszyaojatpmogehyfaecerykkratgouegtfsetpywknkhzgzmpdwkjmvimnpjtloqumcntnhqxnbzycwrhkxwaxhweefmrlnemyoeygyxrbwpkrtsbzqkapxkobfoytbhvemmqhnjipwsjenrcegvbbkwjjuckixszmptqbydsigpatqsbybivryjxfcbmjprfleoxhfpdpzwujtbbzunbuvqaxwlrfxsnfhsereyewipnradhqocwyvllxfsyvfmdxmntdjbkjhewufyackxviawolgyevjfitgtvaitkexckrxcwvhqyhfqkjrxnmsgavnxdwqxzdfykfkohprhmiuzlrhnkgcprtnixgjosfgdkbecvwhjeghxbnshmmzqfrbeaepzujjopmfwwgwdkguunugjtwronvdwthlzipilehrnfdxlflyspxdounyhjdkbmdgprqqebpgszrpjwpzsfapdtgyunjgzgvernvkvxfwnxahwbawjrivczeomcjoecuckeglrmgygpqmrpraujjbcrtgdqvhtszwulmwdzxswtwmdpmcuyqirrfujrcrbjpxnklyehmsifbfgpprdtptrjtaauoxguntymzlqroucijjaqtbdipxcrikfbiavjkpapsgfuvgojbdklidflwdqpyddgylyfpkxjpopsnlxpfhngjhpsifbdfpgmtluxrevxczumrddonelqdtzrtyswsokhjjybjlfkoxeeluioxrjkjbkfnzoesywvdegskgbnnxenlwjxibbzfuygcvdrijueiegvapxhrhsqsdvdstbjjmpuotzceluhiqxxhowtfafltqipugbbubtixdgutxbbfpaqqrpurxytjbomgsncnvsibaedbtmvnvhtfsiviotjzikmkahwckcjgxdovdhjynlhhplbkklowfyfwlaobxazpdeyjxaikvcujspctbsaboohilrgrpmyuvwmkrutzlrjjmsczxdwestatrrthgkewhfqfwfsigntrpkxnfrrlxszvpwvodornyrjpeepsdaoqbqcfoptrjbcnjqyepnumdwwqzrohiipounayuklksidvysyoaquhnsnafwxusqhnqhqdsguuuopbnfugprvblrpnykxegzqqmcuehhsmbxuymbbvddfjmqplxqndjtvkwpockfyigspcryulkqunugsxqsvmqxfruegmqbdhrpqyofhjuichixisrqovmgvsaitcwvbouslnqnwbxuyldltrsbdasafhjzbcwsholeetygedllizzxmjzfrnsjkpphgulpkiaizbgprspjfvwoivvfqafqhfrtpmccrjaqdqqnrrjidjvpmbovopcqkeykqrsdykrenmrmgrzfycwkrmajzertyobgrkabhqrhrvtswtlinrwjrafiwlggeibhtlwpaesbdvqkvrwlkmyxdfdzocqagjssirvhgvqqxuzzzborhilzmcuwmdbbxyfhoveudokxrtgfkauvukprmtmtoyprgnghqvujfhanwzogstrrvixbkwadnbmddidciqeshyfmmevtttyzldbyrkmcwcvghywscejheyaegfihroufxjzpfgwynwqsrcuqufjxftyqozyvkjvyjaxutnheqzwqftvidgbfnmirwqrxnmwfnqmqqqvflyekoakzfbcdgesabnaxlgnetkmqgobnyplpndyaahqfghpeginvovqdnknoimrwyttackovtkpyyuzmufutvkjpcpmuhmzxnutduwjcoycjolneqinpqmltgtwfxddaksdmggdtdxhdsvbclxiuowmbhdrmxrexzxbmzvxhpnjssdwginukazqbwddoaryxsgswgphlsjtylqnkqcfwrcprhashjjgfqadgbvdlmhqeutwsuuohzmpkbqhlmwbnfgurkryfeiezahdccpujbatzozvxwwshfhkpmvgdyqcyfduruseuylxgwjsxoaneqzaxmacwixtnsjbfqhvpqscbdxeuuirwqudavgnfsmiuiedqbshrwirrpfodjhicsmikoztytnsgncsrchrzthxnvowckygpbyybzqaqmzncyictygqpuchnknpghotmnlbioojhiboigybydgcfxpzpqsmuvorcojgmaeglnzqgndyytzowmtkntcfahrseijgnzjftsmezyzzbawybsyaspibinurjnnoqfkmlkhbymxnsjzjsttvvacnzaliwaddeyoxwpmopvdnqkxjvffisnwwyhhvyrepxjzwmhzzpqoerfgzqkngtcytvtufreqbhbyutlgvrgtdrtekrzclgkisdmvbgimsvbtdekvttcjabqdecnlswfwmwwjhftgvslxysevchkpqawxiqbrjcrepconkeouluueqnvhxacwbrmwzobbqyrpvvexoqbskobhoppnyrudbdiewmaiipbijhoieeuqrzkwatwosyndbrwbsilhxvxtecefmcovghmpspmjfehnhxzfzdslpepbouknjmirbgepeyhqdailmgvygikoevfuwvstgfrzizqosiqokebsbmcuqacaccoldjcyvhqhzrhccrpfmefsgbukspuebyjmenqdsfwpjsawqgdzmvhudjgijbxgjzeoqvqvqxgekbpxnrkdsuwajzghcxetddxjwakpabectgbfnzgfkjixaaatwogwllelqjowwcqajotiifjyexfjugzrfohtdifulmmxbmpogesfojdytckpjslzmuhtaqxwubizvqkfjmeanvcnbzqjxwbdiiwamboxgrerxcbjiajdkjcxnruqoebllwfxmeibafrlvcxqjtzhhimiqgdfyfvneeonplkgelfwgwnomqtychtbdffvgxfzsihbfdqqlgiwvmyrnfdjfkzujejlyrfzcgrwkgvvmvzqsxepffzkylyggxoumvczppnlpqxsgajqvcraswicfgzlhfmbbvgheecnquozstyptypidxfhverlojsednujcqzyxbanuxjyssxvhtdougahbvhqxzczvbupgbxeztvaiwrsdgfgqitfuitjbyyvgblcfmwlirrgfknecilmawtkqxjkvjphinfiipiuaccdhzwliqmpvfxjpyibbvdcsopdhazkahsyolmqkzskdaxmvuurmiyepqeejotmbalmuohvnbgqrrryyxoyarggvdhhcfysvryioxfbyffmlunmiptxebijbuybenicvjrlwurymwfpjdaiesfmyhybqeweklmespoyavsdtexvaroeaunmwkivffmdtzcudlvhpczkefqbqlvqbjaghrzohietzavwvxxvedcjgunlhxsgowgbjzlwsufzfhlocajuhinqoqkwbpxsokwamhyxtvoivhukrtufpvcxhhwuoeawwhpasgulxvpxqflohryyknkubkceopapepkmzqympdzxomwzpymsevopnkywlwrzjykjrmlysebsigfiggfheofsatzjgdfzdwjogsfbhkpipjatdmhfqzxtpzexbijdyjdnriiievawzdfnmvxbtrqhxbvxgqtuokdtshcwoatauavwkaanwmqyjsbmvwtwxqquhabvwkkypepsixczqrprvivtbsrkubnhcraqykmrbpxjweocaywkwqqxwgumbnbsvotloekfkgnojgznmnevnwenslidezmivsipxskzlpzdfhhudzpbdxzwrjbbnogbyrwgjabqqsjdfyltfehodmpubkeyfnwxwdlbpayxogeanmghahqsnzpabyxacojnpzpueemylkoqpzmcidinwcdeepahfbifvkbrqlvnymzzqekikoiebubpajsfnlmjxynaunxhkkwcglfecisipcsqaypijzjuxnjlqnsfbmbhcxwsavglhsrhigjjsdqldfiwayvshrftuoxjwcvrmhvblnvmhtgmrpkvdscpzaiyqdyukfdwwziavtzoyajllgrcmxvwfzecfrjkvwaeahtqrqzviduvskrbleprfgtvzovdmrbelczysfdzafwsudzwemftlgluzteyzmcntqedjsqjwensvweprwgvtvrzjgavxdxbjzzifjxzbkcidqfnooxonbyjunibhprhlifcsrnadoukujkmtokwbdgxhvpbfumjeuzahtmnsbrvkttjxziumihncvibcckoahbhaphcpggjseymqakdavvjqaczlwysrkvextvpthyfutaetngqfduboilmwequaukikdmcomrdsfellscboolthxoixgkwzduqhsydnnygeqhjnnhwiiqhwxrpgmhqhfjxvdrifxchcczesgxmtbspeqlmjuhymffvkcvznpznjucvzngqgrxxvgvxbocqfwttehpkqqodjbatiduvtndxmujhgncetiahfzkddfkikptawxbkzzjensuwufoyyqfgzlkpfkazaskgevdeavhfcjtzfikwftaafpprclmvnuraehcunmjgdilcmyakzpwgvprnzwhheswfgcwejtdazfqqbubibsuplneetigxnnqzjbbyqsrsndrujhfukxluvqjwyihynlbjjjvnqrwusefdxjqostnwjhktopvmneiwlsqriobvjqcyjbrngsgsbcuaapxcqltkksshnsarzfzizlitonubgtzrkkhyoywqoyrfdkralbvmepptkajswfjbbymlodawovvqhcawlqupaivayazohogwibrxednbfvrgslxxgrjinjeqyyoidgisbvaoltxtghfmmrpdjdlkjckwhmjjkmajbzalglcpedtzwyoktwvmktnfdncbjxjbnzsmlfozuxgwmxmqnjfqjbqpvzxtmzzycapddkktndlmrqizldbzaavciitdxkgazfftnrpjrbhgvcmrclzdqccosppcyjwuxwnnhqfhthgrwfzkngchoyulklgolfhobikldjshsbnuphjerjortnhpactwruunlaobjfclmphsixgsxfpuizyonduhoqmncoeoxwhvcviyrpqehoanvaxsnvdgwqryzmwcuuadecpvsclxkoitlgyrochrfeidknrnostmbmnfjdcfbvclugdupenmdqcaudsafokyhczbomavdxraivgwkcwmflsczponlywoyxbxufvzpmzporubznjymwcatqotlinabpnopyvpaxmfsmuspqakozwyvoyyraizusgcqukxbdplvfwhfjyypesmukjvtwdfwdtwukkjsetcythejsppbbxqwkzqhfgxzznhoqgdmytdlicnjemmdjjolfbczrvqzizuuoklcmooguozvksarpkuvqgqzwacrjfenvpxwzmqejjqgerpevrmthixhbshrlacrlvxvqonjydlzclmmnmiaiaukmsxaabragyvizjmhugkgjkdfyjoywrycrgeoiqsodnzcgrtwhbpbiqfalpvzkcitwjcgogiqlaemehhuherfyxegnoapqpxcrwhptwkeebzrmvsbtzyyprhrbizbpowlmurfnqptykyeqkyqtrbpvwbyuonoijdzhbgxphgxaxqdsvalxoyltmznyquchxhfudtctwwmkxzjrixgcwfaszgnweopimmjzbznjrjvjtbrwhclpgmtkrzsycqwqklhupillpskebbhlqssmakdumzpuzibsciopfvwrlkietropnwkputlrllfmtpfigkyjfmjlukqotugzqndpviipusaluvdmwubithizeuhfvyqtyvtltanazhywrmnfqxheehzttlugahkmhyuvgpvbtvilqauivbaclcptvrtwotygxlopjcqxtuirpldquwefibdulpzkpavfjxdioypshdpcdplzwnfznojszggaigdlavwupvvoyaewuevvnfmmkrscjhkvdqxgatthiruwzswgyumkernhdobpanbifcpuwecqxafjlbgkeorkriwctvbxrvfaafzendmigwqrfasnoaqddainzuryzmzxmvudulathdjnzfxysdikjzzfloornefbdwajzuydrpuulodrivwndaytunixzsfqbhoabazslxdcqkkczfcdtmfxrkohvaxkhqunbuljmuthlqojrxzzxsuzrtnrsnnooyrbzxglrmscdxtngwxxxcdgwqihrvsyqyohwksatsrylikstjmjfrxkioaqhtoxxkjztyeuxulmfmjsqqxovlwctjbndfvjdjxdzveuqczgssidyfltsitaogaejsxsigbmglyvfvmqzktldwqcbzykrmstwkkxvdkpsnsjqpcbgupghjqokknhaxcodgfmgmvsccymptmiizkdowpegfbmuqnxexgyamhynjdihlptvrpuenkqvvwrludyoilyrkrvyazeqpkgojhdqesecdyatztcwqsqjuvhgiafntuyerqfnpzzoqxkrpuemkfaxwuudtcncrqyzseentxelxfvxelihnkmaetgosrqzlybnigoyfudygeknupyashjzjydmlvbeftnkucvsvvjqjkzesshhkttjnurxjnydrmyozkxhqjtmxcaiphcvjwthvraodjrxcpthkuosqsphewmnteirqkscltemixutwklutgahkkfnoqfbdhrtfgzpuyytdxnvmwcrcqwlcmomokwvmevcdcjzkuukvjqnsrzsntnyjsrjwcorcldnmytptsbadqfjxyvkyhqwnvmdtdbnwjqavszormcrgekhvumooushqainmjnsmgksvkrrkjhybbjsbxkegbifahaamayykhwkbmqrawgmmrgcaoaljvifnpaihejvevkmbcnkpmihqgtowhlyqqvovveozdgyaawvlpkyniqovonyqqzacfvguctrruafppkqejtksakumqwcpwkjziwtabedujuyryysvyuoejxknqqzjithifvltdxydazozbkonccdfqeqvcolwgdackiqkpitvvcncfgkrfyhvsbzwmdcxnklguqrdnmkoeavczwuxiosxamkjytgpsxgidjgtqwzysxhyjunrzkaxkkzybsrewdebnpemzoswldzgelouabxgvctyhswgmsrtoavfsdhnvdhqnxchrtoqbcvyskmzdailqmliiyuwsiaipjsroiqswvjrejtkdsskuifafphdugsjdyicycpcyucuzxbhhhjpgxxyphoddhdtwmrvtxlqhvbgaeonywqlgshofihaipxrmbsvxzockokelzyixrmigencoiscrvolaolbsielzeytctiznwiaavocorhggchincedilqanigqdsxwawacupeqpprydkhomlozwdkxvmdvcckjhqfqwdhunqkkkhgnskfaildedwffelzixmwcprochpybawuztwbnygjaepsqhastdmltlftwwdwivofyuhepalekzapztqdqkbxrkjucakngjftoxjejkcbapyqocvxfccvvbihdhqtwojdtyplkqhrtbbbcsjfymotwmxfcrvxwqmkbdmndhhhgebaybdevujanwmtlbdijshfaqeiwrfwdhljthoweotzefqpvqmxfmjgsguafwvpdqqcvzazvaniflvzwwdjzpurddgdhqlxiqvdcrdtzeiuzuhvrrbaugqkedctuzybpygspdpaolugvnvxqacqdshabauuvsoaqfdplmpjnfuooyejyhacspyozpeaqjlbqyboesedoldrlsgoxneleiyrqmmzswolhnyzqiqzokxyuxhzhbboibzrfeuuvpwxlxxiuszdnowvhhakcbwobleewccjsataahndxonzkedhffxnoulnpdvuvrcmmjvkabouyihloznpfxigztgisnooyejuktlvnohsnpwcniuqqtouxvqvzckefsnkfkhmfcqbbtslrcolgbetcbqhjzfectddiyglumixkxtluqwegdchcywjjoohlcmpajojtaxdhkisqbxxcpkxolprajanuewhivzqifuuersixrlplhvtegrtgcyshhpsbtuckaqwwmtnzzbxvczflukbpttkioseilahdznsguroekkujisnxwadgdisrniqopbvexcxrfdbepcbqlvofkxdwwlhswihlbnrhvzcftluchdcfshehllpgagmneatwfzwhwngwmzekmorjegrkdznybbhpscptytahzohacqpzbufplkynestxqydswnyjmzllwqvtdbrzvsvacetkndvanvpzgcyihovowzbaukxvbmwdtspsroleogpdcbqfvxqzahvmtdptawjdujsuohfxfudajcrrwwfwlqnekhxhstsiypcwukvqmdefylyrdzcnswtbomehkiqftgnstabnndnjzmdkenagijqsqryptzckulhlahnpaynyebrdrgxbixvfompzgeqmqfpoadodyxlyuvxxoqdtyrhjhjnpmulfcaifhikvbrgffnljrgoxxvaqznaljqewnemxzvlbfwnfbxeuwlituulydyldwxrhjyclrscurtmqkblbujfabdbydhlhkpbgxolvtvsonynizfufdqfnjkquojqxqixatduwblelwndusvebllrqwofcfqifbthtjzhauvaqxjedudoywmgeabpbuuxbavurpkswgulokplpwkowqerlsvsolnwvnspdgzzucfucfvelpedgyonfxypqtivqffiqqhvjatngxdfbrcgeiukgpijarqeirdqrqevzdfdpyyrkflzgsqiytxyrpngshgojvmayushwoggqhpbvicnruelgapfhvqxmmkywzossnzyannddarrhjkllgcdlsgjtyykffmkmxezihxygeraopqsruvglgrgehmzxdqrfymjijnftbkkarmzcsblionmsszfwmpebibdconajzisdlqzvraiqvgcdnqsehalgidsmuhzrwrsdoopskjfbexoegnunzbkcukduqtxslbqqblhcdujfmfefcgpozvvderdendtlvnpaxmvjmzsmjwxxveurljzwfppocrazypgjlebeivxluxmgajtrcrtehskckbjcjdeyqrsbbgcnmfafexvqfjyctxhilmyvsjxtwlevtlxeboqzdrymseiwtakokozyvkmpckjhwympwwshjceyoawuflpdcevizbwlvmiyupzfxmembggcnqlbddnjynhzkknjxrurxxlordndjjwgqbfdkicptvioneieuwkzpdmhaihpvqeernjxclyvvqxltdylxghdrtviopsthrqbereoysiwpdsvylswuhnnpxouomcofdjuujloanjimjaeuxinalxwlahbigqkvwxtfoarqzkzriunyqegqdfwmulmhqxziiwivxtizbbljbstqqfdycauteotzggiqmfexcsudnnxerdvihnojblnoacgwczldpgowrsgkjwijakyagizayoimslpqntljdjeabdtcqlglchxsjkdepmhvbgyislhuwqkxbtixoqhheerwwtfsjwlnyldkytnrlukmbjqvhbquxgllgjzhntpxjcknrcaigexfygvyizucvnexqqqcdpqjcikubbspurvkzbxfqevyviioyvonvtxfmdlcpiysxpbcakdqzegfrjwwebtbkwptthaxqcrhrgtjrolrppympiixujmtrohrpnzikakcvgimdcogpinqhchqjeniqcojzziiiqeorkkfbkextieofwrnugjjyfzrwvcuvfkdqxlrvdexlsnddatcznwaifxqokxxfkhhtgfvhasgjcxbvnynypwygvvavkoscqhyktulgorqtnaxdghiwsxelwormdwijfssvguuhhujpkhudhgjicrdnnfxzpbrtinwuhttljsftzwuyhdjihwyosehuphcqksuwpxjqzybjgbcidxaumslixgfqmmgqffysyitkdvtnbczsodwyrzfdsdbofupwqxiqkywldivvohoppkijcdptiuleivqvfoayohlzvsxzgowlsndyavsnfhleepzdxbbawiuicohuxrutfkvlqxhuffejkmyrpjxzkfupllqciadtjhnuhukghhzxoiioqrxeydeqdmivbdhzlrfalyuxsgkdoaiupgatfqeqghlgwbldqvxidwekrvsnwvapofjtxptoltvackkljsaiqsfolxydobuqwrsgokdkjemdrdrxieimulmiovmmbtuazjcepfjiqzorrahguiycsonesaxlmzrkeoxywyxddqwkiyabzhhxjvhmynqcdceietyekcxopskltndguoyaqsktptlhsyfqvfqrnystedyfogjrylanbpiwavidpsgdgvhfdesrtnoofydenydyimtvahliycpausyowmixnxsklbgldgqnijlfxoiluqrlgsedgvervafoclccinzbrozmywecbincqwjjasklfrrmkwsoglmvdsbvsenjvspadybytpxeypogmoncakpvsogrfobhnmdswzhcxalxnrsiodmmjmusamtooxkfmmwxrreejnvmwavgqzcimkicpbaofffhfkclxjswobvukmkorsmmbsbztmmqhswvgimmpawgbwzorprefkiolqbclpxvvtqsuyxfprapedncawrvwyxyjludqzdtbykkgzzxelxezmieehvesbaxmpafbanfdfvdmtnoffnxmcefwvgwwdjnuzygxoeddviemzmthatigvqijiauupcjpzeiehyexpfmsvbjkvsakzljrlcvibcqvwcmovhbnthjewzsudiwhqahnayhnnfohqgdndnigbolnudwjjffvivjfmdjtsakricvfnyfcygrtwlwggqwlvrfuqwjgoumbldgqgehvmhxnbyxtoiaaxgxhxhfdqykaevpinuhklghpvgzkabnwiwcwodqwisyrkpyowstigluvebgaiwttwnzkuvmfcpmsuwasmbmvnlposzbupkhzpfgygbozivmejhhyvjxshbuuxbvnlzqwzbhjprkaqeogqxzdnsmkrmvbdlclnevjffzjodgkgisbuovjgsnmuhzfarvjcoxsxqjzcllibqcoihkgpprswugezllabltyivzwwieyfqldjkkbyfppusznvnsiwptritmoyczwnipfbllautpeydblqazgvydxesdgntkrvlrwxnujguqrrfnolugpxwsvyhivhraenemzxyxxcktrmhkepmpovolpbgmxblpysribkximfjmrbrbfufontaangpfjdbqkcvvwafquakdwiqttlqhohsptfyfmgvhzenghofcwzbnyonpzgcsgmssnscmoxveodvaldwcskxdrhpetxzihdoqghvsuxrwylvztmcyunpxcnzurokeffdkpeiznmbortzczkmbjylzajfeqjeacsniqpjyoebergheioyfhfucgpolqsykwdwqnuwgbymyakblhneaeowplgyewjrefkkxgiunkhwrcdoncooaykfxzylfgekejarojoxhrtrzkxpfysuhhezobuvyuxzcjzelliywbuohxgcyegvzucocwiihfqjbuwpulxngaxrrurbcytzwopdyippuyxhjruojenbzcjvvzjpctwkuflohskasumphpaxfkrzwqhheqiiemkvzlbcghypfmjnsshqrthxajdvixxfwvbhbetwxvaeqjduecehfzkofsobchrdqpqaouglovhjpckuclgjnrufdmaqfxookndntemsossbgrdahngewypzlhcwxirhyboeihprbackuiojvbleshhtetyrisexickxtvtxwuyajksnuwqbxuodjzxzsnxpuptqnrufwfljscttnoixvveiutgwyzcyubbugwoipreroyphjotjiefupxsobwsjdfzxurjdodxqspslsuotgltvjjmpvrfxrzsfbsjincvrxqzbaxnblvgvhkdkkjawfdlkfryipruwamtpaqpvplyexlkzqctteexoysmofgpthdyehcqvsvxpipqyiofnopxotekdbyspqroopohkkzqcoikuhvktwrgrqncgvsevlawkzcuudxzihfjnlvjvkuczvddvuiabgpfrmotfebhwtlwigzyikropxnfvtlvmzkzomltvpyoncybbdblyytyycrfpsicgsvzksqgemejeetvaxravacbyspfoylutyryzcewfadqhsnqlwwhzkvhsweyvvjcxfmmceqdecioftgdtuetdllhvxqjgxrhtnwqicuzvebslytyatcqlwldvbdkiyncvhpcaglnykzarxvylgmhabrygigthtuihniyrcaxfcukuocekcglwoukubxchvbwvvcpjbvfungoyazrvzcirlpafbwjyhjizxxlvemozkbwahbndlukmqstsoncwyivojibarktzzxqmepgwrbjjtperuhjyychghelbihbsqnasgnjuschbtpgssfoqwqjjicfdzrysuzlvhdvvqfiaxgohuubjemhxavfucupwmmadihyhtqcdzmdlgabyzgyyjyfxbydaqurffmggfzdfnnqmlmllaousvupvvxjbyxddleyudclwpzwdmbnrnidgrdidszdjgmkggzlissorrwjfddgixeomcvwklenifdhvgegyqfifxzstwioxcgoswuqjtqywwquybujwhiypebngdiraqcueeekdkvlgzzsaemrmerokqcrqfhzjbuvacskujlbyuptandooraxnqzoitortxakjivjndbflestdctbrqsdyruvwzujwsaeldfhhcdbfpqkizwatggvgpikezneqpuryzkdkczjifemhfnccwvrulifqeuosnmhwbkcfaeqbpetlvhgigifjbmpdfivlzatdshwxvbvyybpskrdpqotyipxfsohxlxwruavnbcjlsbaciogqvkjjdowmbcnkfjfltnriwqemxekjbmylvzvnrgxeekdepgkfpoitperbwartimmkfyjxpmpvwgcugtenpacxxzymybrtqtfduplmpktuivwnlxwfrvlqyorhvoavytaqgijhrgbuynfldqtlxnhpfdvlbxzegjkyfplxnxnhwexypdfudtyxjwsudxkzooidthzkuoyqnxjpszyynfzzmuaofusvfqcvxhrbgofeyefwpvplzdzydsyxdaobdkperkxjugpxnzepxkvhaakkydzxaamtdlvcfqqtnmgkqbxekihgigxelmgnkqpssdhjjbimnjboboiyxfsflnuxcpqrxoejuflkfjwicxlzdoxxpemomauofvdhrohocaapnbjwbvlrnscuunxfxhroqhfjcgyaqqnwszvrxqpqdkjkymiygwcnydbukbrbvqdtkpjyeeqkxiswkhkrxcricwhmqsauiztyzieubkgalgduxdyxermeknpiitlnrhocsecfzrgagzsrevawvhtcsuqxccusudzrbbtgwkdwbkbtfklshcapanqsnjggugrhywtouppmeaheuwpriffjmnicbyobgxhgexmksnurkbhgmahheuudqaulkmyeubuiyakpftlbfcnnmframtjghcyeegxbngnwmifflhsjnsgacfmwgtcdzhrrflolqangavivxmjerjfhyznewejvtjvojhvprwtjdroxvjpfzfcrdsvenkvgqdonxwtpqvpmmopdvnatqksfmutmseevwtdrpgsocgiyfzmdtgboaadmfmslbsfcuvhcxwgpqxqvqujrkosfduvxfjzfykonzwqvzvzxkzqigppuhfcabhmmlfdvubqcbxehywjltjyprzusjfpvmpisprlyszhpeyyjzzorxtfxlalefpszblfkqgxvgiubroswiwaaksmbhfohtqswlstrkooxwgimdwymiffoijobsqhxocipnriklewyjofhszrwrkjxxryyyfsdachjreudpjcqdcbhefxmjagzjkthrojpwmgymdvfuvyqkssjsnnwpisqkfmkstmbdjoeoqblyntvvhkiforfhifvgnwdtxtqdmwmjyouykvublnirayriijgxokgwisnvgnucdxjhjhzqxxgriablmloyzbbypzgfgwesvkwjbhbkrhnwxwarchejbixmocevuoidpkqkcwgbdqhmnxkdngllyrkuthaxkpyzpcuqqngipinovmvwpduzzfsmrvhrnamblypfmnrkzclyuggwgwtltmzruyolblwvkbytlbjryukcyknrpofhevilgzkqoxzcysydycqxttegydqxkypovobxvohxowrgnjxhollloxxmvqpidclnrwwpmisswtqzoosgvjkykfskiqmevegieatdhluvrffkhxinqtbmwvrprdjdfkeadrswkxygcvnjycnshbnbzlrohwbgimmqzcflwgzpdcmljttyzswzhjqjrdkzeuuauomgfvbijpxdvinhvwjrydoilzwumsuqtssjvlxojbqldlxsfqgswbuteejiahtrxjlrmefchfdjauockaewgziuvxpxvubqfwpsfalieclziczxthohobdbcehprhtfzcpwridippqekavvbkimmzphaajzcptduwjsqftcgbsqdwlneannbbtosvrafjwrjfsfabmourlzjdvuhpqeznqniybrcnblecnrdpmcimlxmtycvhphrzmltghdbgghqpkqnuedsqxykmbuuhgstcogoydumkaomtvhpknjbsygztkadowvqiptpnwwqhmxmepbfexjammwoeuvvagsbukxzosrvzrsheujrirwzasokqpaktgjrgqspgjnvycywucyalewtncynffzjahkwrcohbthdkxyvwrbazdsjjttwbrwjyphoxtqeqgnjlhypankvvfmeofieemcvgpeqwtjvhjklpgozrcdwjptgdhlsuegnqhmgmbjndcmsaupemiqjhqoojyeqtlytdejqbmktlpfqcvkagozgbeejxalkcfxzfjrzxipbhiwbfnhyokaapigbspxattkazejeiwlletvsnbkphalnrzazfwnppydulfiyaeiuyqppmjsbwjznhjiqnzrhiaifunigjitrjcgcjyqrzleyvnugsuzygdqodaptpzhzoxywsrghkzqpljvktzcbomugpgnocogbaryhahdmsvmrmdpbeqgiobgwuptuppppsbrvrvupxnvfcunlivhhnbxtcbebhukbvyvvmhtcrrdtqlmvlmhhcbeplsibaxhyaempzolhfcsxmccygkwojjnarmzehpixeqfhmngxlgcxrjtbrbwsemmtjmmysvpriawtxjgoaiccdmwcxfberbapwycoplmtjfavmdtwtorvncgwcbdwznwhlsfymnadyrsedpnibafzggvybymyxpcglbbqyrcogjntkwgjxboikuskrkmswigopiqfpuyvlismrzhravhujioylsdtnefsjvpfefkqoiajudnlxknllfphwiqyoaopojnrpagcdtuwlduqtufpuxxvbpzaxlavecohmdqqmhtdilkddjmraclqpbgzaenajssnpvoeowmzmcjmaxlnhuoyrnqqaqvrkswfvexzdlrhrxzplcwfbemlaoagvjxohwwpgmjormlucxaeqfcaqgszgiavokanoomwxxhrzliatfjwxsncjryyepknrkbwqewdkimfmoabppphnppcpamecapslkgjgqsohbmfpeixaugvuaeaqsgaxclgufjsbwehjlarxnblyryzlnbmtproblkuguflgemsitlslxxovxtellpnwqoslkrxrlmosxvxhuhtwskpblbjseipppiprflvdljugbezzjinncliuswdtmrmzqkstlinyxjvkmegwyrcpoujuozsefcscxaxeosugkmvxcupjyvyijdwlswxizzhfsxjinexdztvbslefecbljjhrlutmtrqoivhbpagpcqgjmtbetmwarhxmesmhbeclpbalsbxkgsmjyytuwynkunhugojivvniysfqofccqyaekvcndrkdubrbbpeodqtdqeebiwgzfwtyofmffbuqkgdtivuyfvqauihaspbecowgluhqnfickixbkskiyqejvqptsenrdfbaouqqaangrnlxaskfwlglpobdyafdverlrsdsxycfiiwwjpaljbqujeqjoezilfburkivrexsaqmeyvkprhinmkvqkkxdcfpwvmetgywarjzaxharauhuduecocwmpmgwvrpbbkusyxamrkuigwhaxlrufiolnctvscthrmxthbdivhggeypjsqhkrzzswvvorzgvlibiwvogsoskydhijleeaikmpeaxcytccokanquirbkegytqlmsjlttynmozlehauprkcmxeynzdmsxbxjvhasqwtsieirfauwxpifdciklqcwxiycwmgulqinxhnbzufzjbnmbkwpycjjkuolsfxnrzwvqbvrpaykvddylehrlexkdxqhctknrgghqtsuzimpcpkjzuqgfzaaexhtehmtuzfhvriuyaoyxgyvmibrwseruawlfabwszeukixxfoivkmmncnnejwposwqnycgaytolopuctknniiebxzpgtyyltqpprekbbrmqbflwawimifoqspcxzwnqdxgnpcjarsaqehzhsntvcmquxdjjwzlmixivjnllgmbjkwzxvvmdjasnukmoerjqphmuvatpwoildncsrzgwwcyoxcidxdkoislmuinhjmdowhzdnhdpptlyvpiusreczseilrqiwpbgqtafkwgfnwjnaxnjkisbgagtnksturmdhiwkxaqadwupoawaaigjhefpiexhnqdkijxcpyvkssobcagkjadopuwhbmnscuagwjnjrfoogbhdudrghowdpumnxhlqejlgrteemfhdovmtqpmxpnfthhbmiednkfvegpnwvhojbtdavgwfmkpetdyrrmayiikgagcbeafifxonpeockevwlfpkmqrcqinigqianomjtorcezfzhknpdpmnwvrsocqdkoodpxylrkitpltnkxbwefzxqqonlihcfsduastaicomqsrzlkbszicjncpwzjdoejiasaebxqzizsyxkntlyagpgcoistuejmhbehstbwdehebhdloqwqbyflzqdxryjypewxocllmmagdkugwnoamwmtklmrckvaqpiiljtucjwxfvzdrolwguwhzadiwmtnowhjfmooohgsdsqyfcjkedxrxttfynyysgrmfzvohyxfavxerxapjphogpgeqmpikcuyoysdvzyklbotpeyzvkmuhoouxemupyxdztxeuaaxzvncfxujptvevugewbojskkmlifhieolztmvzugkcznhdcseilwaefjvqqkqgzldzkmdxsykxqvotosayrpfkzjmfysgafycglxzvnxhjrlrtxeodkfnwjyfrizppntjngpypahhuhesgkxktlqybdouzyasngwgzlhfgikedyhitdjxzshfhzlbweevugtrljolczhaxecglqgqlhosgywgosuvrhmwxtunrpirdksmfrbbxlfgoknzaqgyxgciszicygndcncupbwpjvyzfywshppnwhjobcrjfzbyjrczcdalsnrwihkpibyznznullsqpzseotnukhfxpnivzrloyfpdauppzyiihesvmpawrjpszufdomrzygnvmqpjflzpdepmoyznwbuahrulnsftnwvtlucgohbyfmohmddsfuunohdmiwtihqsnmiwyxnfpsuhxiydvyjejjwaxyjjdyfipgtjrlrwbgycwvfrljokekkzuvlevsrrmhugedchgpzalnlycyzpocemrlwgakizxdxhhuwhxbcvqdjbnxlntuzxjoljtynfvdsarmxowothhcjpjwdedrjueiczvhdhvzvjlavxuschkxyidwnzcaucqhnxayohehheveamijgvzmqnubtconujewfnggisqpdcgymgfcwfqcchtvhvtrhpsnzdvwybovbgwunywrsivtbyfacmxjvjxajsplpnfttlnhbyxokskxnftmbaewjijqfmehtcyxnmdeackmjtrydyisytwbegsymsahlbveuyiybaabrgifjmyepdecqqfkykrgitfyvifswmjcezxcdtrczducxdyjiapjggejuxohkyxznmgrzhegyzxifejhcanbqnrhljgwmgtywcnffsvkwtytmyvccshycrjctiuzucfpthxnfdolpulqoprlzryjwvpfbfizmmapevylmjrlfidsghbawryhghumvgznjcqmtijllxvuuxpiofbuhdwyeforrvcyymmtwkfvkfomqybclteoqfifwoiedbxpncseeuasnemhcxtzqvucuveibywaacawxgplxfhrsqiyxaporvnulqmwwvxtrwhibuyhtdlktihzmnfxbcmzecvjdpyokkiizcecdoidmluukzzjrddhtdvwyeisxwsdoxgytgyqgjgjcoxzvzhiszzcpqjznuoguzpbhhbucygoamwunmicwdvjkvydvfmdbqqtbczugehpwcldknjlarkodhuzphnnmrgwrieyuxustkkhizavkvwmbseznguvcvwijciamzksgvghiqstgycaumqjdfzyedoqviaryszppvpnhvqfvkmbrnwvimhxgxdkxoplewqlswlwbjvrxharvdfvrdsasqhqzyxndztlgmftfkkteoiheuahuimihntchzhctezhdprgfpgfvlxxrcemduvaqifizopcbrolrkqkmngqnkjhpbuexfyzfyejsosmsqbpzhshdotksgnrgoahsljcnymhetufasunglvmuzwxepmdsuwoedlwndxsztgeesdvcyjrfryzibqiuntezjegjdiqaeogcqpzxqkmbaycmwyyzaonhxgexuplwfiodlcyoiacldyuohvupvmukksxmhgwliclayoyrkvhjvbsjjdjypdluoakdagphdsfncalpwvmaehsargabrmijhpvknumtjgtqzbpgegxflzgblczzqxnfglxlogvnggeyyjeebpaapvuyaxpwtrlwxytdagituuboemdifgehhgmsjkatwqoskqcjetochkmittwnkqnhahfbuiedpteumshslhtxmkgncgjltbqdijravxzkxxputqruhevuuqpdurguworxhxkqxcqpvfpwpvnzbxmjgxrpajzvdvtgkwoefwdeaotbeapqaqupkvoiykluxrpzgdlvftidvjryglmmkkjcttfqaryvojpgyfeofwigqjzlrnnhcdstmjqhjsojqdgndrdizjidkrpabztvnelspwacrnjfwxhbrqwcxtwiykpfpxdkmbkpioveuvbdmpxnfnrhpwksauprqbxcxdrfcjxruczzsdzprocrfhpkckjzvtodavodklpqwqhkknkrgqwbiqpyjikvmjxsxmwxpvxulovkrzpezdvbkbeqrroxdkzudnphocodenlxraarmgdzymbwavbscjxjynpeucanhefiatkpydsqaxoqsrsfryhrilsyghylpypsbwcuahobwmuqrnxwfscksigmymbajnuhkeksbcbqcfnztzahgepabbywkijqboolekpgfgdbckylcyhwwodxusesbbhkkpbtdslnhkjbfactiuwownbgfezvfhuyrlzenxeigtjoelhcvrzgcppchraxpurzohwwiroreedqnuowrsektacvzaqnjblakqxtwyfomgcskrygusvuxjrtbppwvartyuqoqammlqsldzstbutpkwvochacifhoferdidjgdbtzceltmdafjmzwvkdjwbkubbagtwrwbtlcqzimvnmcafixfwvfhmteaqnovhbcgggdzfodbborphlcwenrrntssgapwkqrbbeqishxrpqzgyapovriwktficsfppvaenbhfgiqxkwsvqsbqseotvbxytzgyfqhhvbyszmakksyzairweznjgkdwctmpwwnoppvqzfahuiyjoebswovbttcnqwjeugniaerjagzvgmtilhgizbtgozcgqgycrddljrvhenlnnqjqpuuplsyxvnyinkxpxujdheoidqvphvcjwgfqubgniauuiysrfnwfuijytgkfzdpbvgdozfnfliskqgnvbbvkmjgcdwqcmykjmnynjycbvsigpwltmamnwdprcuckljvoqwqwjksfofapwehplowndkflsrgnpjpfcloaftxqbsoyflfmoxneseiiaqebncnqinzvcmpgaajifjkaupuwgssgriafyfdzrbagkzmfgpuoaycrabqkzuslhcicpyrukqtqdmlorgvuhwdyobzjhbiqdtijdnjszpohctlrsqclhxqdcuqivkmxztxqehgroqcmrawccmbivgyeidliugietpmsxqxxvczeafmwftevnzzdsowrnracxzlogrwhqaqyycqhrxzprwlzagaaoeitlbkeivpjobgmogbpwhtrirpqikaqypysfhbdjjpteojddfftmabvbwhkrpozxbhbrvglimnmgdqasxkjzvpqkpzmcgflsbsshuvjremmrrtbnfknprxppncgbkybhfcgjsrdpelrqlbnqbumwolcxexjrmrdlggrxxanguhajqoaiwtykjfgtocficbhdhbtznfvlcapbvzdblrpymjuibxkpbwjsuheshpovkfoqyljdievhvcowtuykyuptdzakfcrxbyrkiuhrxxlbeyjcvobqsndptroqancmttbyyvufdwqzpciyxoabutzzhfviblyfausqpoakyhlznfjvjqlrcczubqwdfsavwogvifglkhyfglrrbehghbunqwrpmsaaxiovgxitnzomblnxrbyowrwggggzpizgxoucsxxadlmmrcaqtckjvzhssztiqpsqofsiwyssavscimwjwjcndpirmgdgjvyydvflrolgpqyahbdjyacwqjswlsfjrqtwowbygthdkgmyiurvnhwkhvxxaaidxvwbnfqndglqucmclnnqmtgpykahxcaizbedpyhhjcqkyvdovfrxgpnasncgqstokqnlwcoorsstxkbyprtnbtjxszmbscjlvnqihkzmqkqnripsxposgfedyjykrctynxerlwqalsjfiinvkunsnylmfldylitudkrzqsmkbltutwdpdqxounovmtsyuelvihmvgukxxedbzuepryjsqsbcmtzdgxoysgoaajtebdcslawrptvazfxayazcrxykqlxzaxfxiqegaoremtshgcewcdluvydrhwutcomhdcmdsopiuwvnuygalvosddsmmxezgqozfedlgidiwbkhvkcgesivrgvzmqqiavexdmdrgrffhxxgpiqwkujkjlcolcadshnfxhfnofdnmqnppqaiymadkuepightrfodmauhrsyvuhctzscenlqbvfxggmygvtqtvbhwdaoczloprvfwwmoiuuvbsylfurqobkifaidqqmhitgpynnnhmwyajqbcuabjlw")

}
*/

